const questionsData = [

    {
        question : "Which of the following command is used to create react-js-app?",
        option1 : "npx create-react-app appname" ,
        option2 : "npm install create-react-app" ,
        option3 : "npx install create-react-app -g" ,
        option4 : "install - l create-react-app" ,
        ans : 1,
    },
    {
      question : "In React.js, how we can pass the data from one component to another?",
      option1 : "SetState" ,
      option2 : "Render with arguments" ,
      option3 : "Props" ,
      option4 : "PropTypes" ,
      ans : 3,
  },
  {
    question : "Which of the following function is true about changing the state in React.js?",
    option1 : "this.State{}" ,
    option2 : "this.setState" ,
    option3 : "this.setChangeState" ,
    option4 : "All of the above" ,
    ans : 2,
  },
  {
    question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
    option1 : "renderDOM()" ,
    option2 : "componentAtNode()" ,
    option3 : "getDOMNode()" ,
    option4 : "findDOMNode()" ,
    ans : 4,
  },
  {
    question : "Which of the following is used to render components in web pages?",
    option1 : "DOM_render()",
    option2 : "transfer()" ,
    option3 : "ReactDOM_render()" ,
    option4 : "render()" ,
    ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
    question : "Which of the following command is used to create react-js-app?",
    option1 : "npx create-react-app appname" ,
    option2 : "npm install create-react-app" ,
    option3 : "npx install create-react-app -g" ,
    option4 : "install - l create-react-app" ,
    ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  {
  question : "Which of the following command is used to create react-js-app?",
  option1 : "npx create-react-app appname" ,
  option2 : "npm install create-react-app" ,
  option3 : "npx install create-react-app -g" ,
  option4 : "install - l create-react-app" ,
  ans : 1,
  },
  {
  question : "In React.js, how we can pass the data from one component to another?",
  option1 : "SetState" ,
  option2 : "Render with arguments" ,
  option3 : "Props" ,
  option4 : "PropTypes" ,
  ans : 3,
  },
  {
  question : "Which of the following function is true about changing the state in React.js?",
  option1 : "this.State{}" ,
  option2 : "this.setState" ,
  option3 : "this.setChangeState" ,
  option4 : "All of the above" ,
  ans : 2,
  },
  {
  question : "Which below function in React.js is used to get the DOM node when the component is rendered?",
  option1 : "renderDOM()" ,
  option2 : "componentAtNode()" ,
  option3 : "getDOMNode()" ,
  option4 : "findDOMNode()" ,
  ans : 4,
  },
  {
  question : "Which of the following is used to render components in web pages?",
  option1 : "DOM_render()",
  option2 : "transfer()" ,
  option3 : "ReactDOM_render()" ,
  option4 : "render()" ,
  ans : 4 ,
  },
  ]

  export default questionsData